-- ============================================================
-- HR Schema - Core Tables (Oracle DDL)
-- ============================================================

CREATE TABLE HR.DEPARTMENTS (
    DEPT_ID       NUMBER(6)    NOT NULL,
    DEPT_CODE     VARCHAR2(10) NOT NULL,
    DEPT_NAME     VARCHAR2(100) NOT NULL,
    MANAGER_ID    NUMBER(10),
    LOCATION      VARCHAR2(200),
    CREATED_AT    DATE         DEFAULT SYSDATE NOT NULL,
    UPDATED_AT    DATE,
    CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (DEPT_ID),
    CONSTRAINT UQ_DEPARTMENTS_CODE UNIQUE (DEPT_CODE)
);

CREATE TABLE HR.JOBS (
    JOB_ID       VARCHAR2(20)  NOT NULL,
    JOB_TITLE    VARCHAR2(100) NOT NULL,
    MIN_SALARY   NUMBER(8,2),
    MAX_SALARY   NUMBER(8,2),
    CONSTRAINT PK_JOBS PRIMARY KEY (JOB_ID)
);

CREATE TABLE HR.EMPLOYEES (
    EMP_ID        NUMBER(10)    NOT NULL,
    FIRST_NAME    VARCHAR2(50)  NOT NULL,
    LAST_NAME     VARCHAR2(50)  NOT NULL,
    EMAIL         VARCHAR2(200) NOT NULL,
    PHONE         VARCHAR2(20),
    HIRE_DATE     DATE          NOT NULL,
    JOB_ID        VARCHAR2(20)  NOT NULL,
    SALARY        NUMBER(10,2),
    COMMISSION    NUMBER(4,2),
    MANAGER_ID    NUMBER(10),
    DEPT_ID       NUMBER(6),
    STATUS        VARCHAR2(10)  DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT    DATE          DEFAULT SYSDATE NOT NULL,
    UPDATED_AT    DATE,
    CONSTRAINT PK_EMPLOYEES PRIMARY KEY (EMP_ID),
    CONSTRAINT UQ_EMPLOYEES_EMAIL UNIQUE (EMAIL),
    CONSTRAINT FK_EMP_JOB FOREIGN KEY (JOB_ID) REFERENCES HR.JOBS(JOB_ID),
    CONSTRAINT FK_EMP_DEPT FOREIGN KEY (DEPT_ID) REFERENCES HR.DEPARTMENTS(DEPT_ID),
    CONSTRAINT CK_EMP_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE','TERMINATED'))
);

CREATE TABLE HR.SALARY_HISTORY (
    HIST_ID       NUMBER(12)   NOT NULL,
    EMP_ID        NUMBER(10)   NOT NULL,
    OLD_SALARY    NUMBER(10,2),
    NEW_SALARY    NUMBER(10,2) NOT NULL,
    CHANGE_DATE   DATE         DEFAULT SYSDATE NOT NULL,
    CHANGED_BY    VARCHAR2(50),
    REASON        VARCHAR2(500),
    CONSTRAINT PK_SALARY_HISTORY PRIMARY KEY (HIST_ID),
    CONSTRAINT FK_SALHIST_EMP FOREIGN KEY (EMP_ID) REFERENCES HR.EMPLOYEES(EMP_ID)
);

CREATE TABLE HR.LEAVE_REQUESTS (
    REQ_ID        NUMBER(12)   NOT NULL,
    EMP_ID        NUMBER(10)   NOT NULL,
    LEAVE_TYPE    VARCHAR2(20) NOT NULL,
    START_DATE    DATE         NOT NULL,
    END_DATE      DATE         NOT NULL,
    DAYS_COUNT    NUMBER(5,1)  NOT NULL,
    STATUS        VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    APPROVED_BY   NUMBER(10),
    NOTES         VARCHAR2(1000),
    CREATED_AT    DATE         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_LEAVE_REQUESTS PRIMARY KEY (REQ_ID),
    CONSTRAINT FK_LEAVE_EMP FOREIGN KEY (EMP_ID) REFERENCES HR.EMPLOYEES(EMP_ID),
    CONSTRAINT CK_LEAVE_STATUS CHECK (STATUS IN ('PENDING','APPROVED','REJECTED','CANCELLED'))
);

CREATE TABLE HR.AUDIT_LOG (
    LOG_ID        NUMBER(15)    NOT NULL,
    TABLE_NAME    VARCHAR2(50)  NOT NULL,
    OPERATION     VARCHAR2(10)  NOT NULL,
    RECORD_ID     NUMBER(15)    NOT NULL,
    OLD_VALUES    CLOB,
    NEW_VALUES    CLOB,
    CHANGED_BY    VARCHAR2(50),
    CHANGED_AT    DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (LOG_ID)
);

-- ============================================================
-- Views
-- ============================================================

CREATE OR REPLACE VIEW HR.V_ACTIVE_EMPLOYEES AS
SELECT
    e.EMP_ID,
    e.FIRST_NAME || ' ' || e.LAST_NAME AS FULL_NAME,
    e.EMAIL,
    e.HIRE_DATE,
    e.SALARY,
    j.JOB_TITLE,
    d.DEPT_NAME,
    d.DEPT_CODE
FROM HR.EMPLOYEES e
JOIN HR.JOBS j ON e.JOB_ID = j.JOB_ID
JOIN HR.DEPARTMENTS d ON e.DEPT_ID = d.DEPT_ID
WHERE e.STATUS = 'ACTIVE';

CREATE OR REPLACE VIEW HR.V_DEPT_HEADCOUNT AS
SELECT
    d.DEPT_ID,
    d.DEPT_NAME,
    d.DEPT_CODE,
    COUNT(e.EMP_ID)      AS HEADCOUNT,
    AVG(e.SALARY)        AS AVG_SALARY,
    SUM(e.SALARY)        AS TOTAL_SALARY,
    MIN(e.HIRE_DATE)     AS OLDEST_HIRE
FROM HR.DEPARTMENTS d
LEFT JOIN HR.EMPLOYEES e ON d.DEPT_ID = e.DEPT_ID AND e.STATUS = 'ACTIVE'
GROUP BY d.DEPT_ID, d.DEPT_NAME, d.DEPT_CODE;
