-- ============================================================
-- Payroll Schema - Tables (Oracle DDL)
-- ============================================================

CREATE TABLE PAYROLL.PAY_PERIODS (
    PERIOD_ID     NUMBER(8)    NOT NULL,
    PERIOD_NAME   VARCHAR2(50) NOT NULL,
    START_DATE    DATE         NOT NULL,
    END_DATE      DATE         NOT NULL,
    PAY_DATE      DATE         NOT NULL,
    STATUS        VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
    CONSTRAINT PK_PAY_PERIODS PRIMARY KEY (PERIOD_ID),
    CONSTRAINT CK_PERIOD_STATUS CHECK (STATUS IN ('OPEN','PROCESSING','CLOSED'))
);

CREATE TABLE PAYROLL.PAYSLIPS (
    PAYSLIP_ID    NUMBER(12)   NOT NULL,
    EMP_ID        NUMBER(10)   NOT NULL,
    PERIOD_ID     NUMBER(8)    NOT NULL,
    GROSS_PAY     NUMBER(12,2) NOT NULL,
    TAX_AMOUNT    NUMBER(12,2) NOT NULL,
    INSURANCE     NUMBER(12,2) NOT NULL,
    NET_PAY       NUMBER(12,2) NOT NULL,
    BANK_ACCOUNT  VARCHAR2(50),
    PAID_AT       DATE,
    STATUS        VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    CONSTRAINT PK_PAYSLIPS PRIMARY KEY (PAYSLIP_ID),
    CONSTRAINT CK_PAYSLIP_STATUS CHECK (STATUS IN ('DRAFT','APPROVED','PAID','CANCELLED'))
);

CREATE TABLE PAYROLL.ALLOWANCES (
    ALLOW_ID      NUMBER(10)   NOT NULL,
    EMP_ID        NUMBER(10)   NOT NULL,
    ALLOW_TYPE    VARCHAR2(50) NOT NULL,
    AMOUNT        NUMBER(10,2) NOT NULL,
    EFFECTIVE_FROM DATE        NOT NULL,
    EFFECTIVE_TO   DATE,
    CONSTRAINT PK_ALLOWANCES PRIMARY KEY (ALLOW_ID)
);

ALTER TABLE PAYROLL.PAYSLIPS ADD (
    NOTES         VARCHAR2(500),
    PROCESSED_BY  VARCHAR2(50)
);

-- Sequence for payslip IDs
-- CREATE SEQUENCE PAYROLL.SEQ_PAYSLIPS START WITH 1 INCREMENT BY 1 NOCACHE;

-- ============================================================
-- Indexes
-- ============================================================

CREATE INDEX IDX_PAYSLIPS_EMP_PERIOD ON PAYROLL.PAYSLIPS (EMP_ID, PERIOD_ID);
CREATE INDEX IDX_PAYSLIPS_STATUS ON PAYROLL.PAYSLIPS (STATUS);
CREATE INDEX IDX_ALLOWANCES_EMP ON PAYROLL.ALLOWANCES (EMP_ID, EFFECTIVE_FROM);
